use TrafficDepartmentDW
go

-- DELETE FROM dbo.Place

insert into dbo.Place(District, Street) values ('CHElM', 'luzycka');
insert into dbo.Place(District, Street) values ('CHElM', 'lyzwiarska');
insert into dbo.Place(District, Street) values ('CHElM', 'Antoniego Madalinskiego 2 do konca');
insert into dbo.Place(District, Street) values ('CHElM', 'Ludwiki Marii Ludwiki');
insert into dbo.Place(District, Street) values ('CHElM', 'Jana Michonia');
insert into dbo.Place(District, Street) values ('CHElM', 'Bernarda Milskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Milocinska');
insert into dbo.Place(District, Street) values ('CHElM', 'Feliksa Muzyka');
insert into dbo.Place(District, Street) values ('CHElM', 'Nad Potokiem');
insert into dbo.Place(District, Street) values ('CHElM', 'Narciarska');
insert into dbo.Place(District, Street) values ('CHElM', 'Nieborowska');
insert into dbo.Place(District, Street) values ('CHElM', 'Niepolomicka');
insert into dbo.Place(District, Street) values ('CHElM', 'Odrzanska');
insert into dbo.Place(District, Street) values ('CHElM', 'Grudnia’70');
insert into dbo.Place(District, Street) values ('CHElM', 'gen. Leopolda Okulickiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Olimpijska');
insert into dbo.Place(District, Street) values ('CHElM', 'Pastelowa');
insert into dbo.Place(District, Street) values ('CHElM', 'Aliny Pienkowskiej');
insert into dbo.Place(District, Street) values ('CHElM', 'Pilkarska');
insert into dbo.Place(District, Street) values ('CHElM', 'Platynowa');
insert into dbo.Place(District, Street) values ('CHElM', 'Zbigniewa Podleckiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Pohulanka');
insert into dbo.Place(District, Street) values ('CHElM', 'Przemian');
insert into dbo.Place(District, Street) values ('CHElM', 'Ptasia 30, 30A');
insert into dbo.Place(District, Street) values ('CHElM', 'Reformacka');
insert into dbo.Place(District, Street) values ('CHElM', 'Rogalinska');
insert into dbo.Place(District, Street) values ('CHElM', 'bpa. Hieronima Rozrazewskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Zygmunta Rumla');
insert into dbo.Place(District, Street) values ('CHElM', 'Ludwika Rydygiera');
insert into dbo.Place(District, Street) values ('CHElM', 'Gabriela Rzączynskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Saneczkarska');
insert into dbo.Place(District, Street) values ('CHElM', 'Ireny Sendlerowej');
insert into dbo.Place(District, Street) values ('CHElM', 'Aleja gen.Wladyslawa Sikorskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'gen. Kazimierza Sosnkowskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Srebrna');
insert into dbo.Place(District, Street) values ('CHElM', 'Starogardzka 22 do konca');
insert into dbo.Place(District, Street) values ('CHElM', 'Stoczniowcow');
insert into dbo.Place(District, Street) values ('CHElM', 'Straszynska');
insert into dbo.Place(District, Street) values ('CHElM', 'Karpackich Strzelcow Karpackich');
insert into dbo.Place(District, Street) values ('CHElM', 'Antoniego Suchanka');
insert into dbo.Place(District, Street) values ('CHElM', 'Szermiercza');
insert into dbo.Place(District, Street) values ('CHElM', 'Szmaragdowa');
insert into dbo.Place(District, Street) values ('CHElM', 'Lubomira Szopinskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'prof. Stanislawa Szpora');
insert into dbo.Place(District, Street) values ('CHElM', 'Wladyslawa swiechockiego');
insert into dbo.Place(District, Street) values ('CHElM', 'swietokrzyska');
insert into dbo.Place(District, Street) values ('CHElM', 'Tenisowa');
insert into dbo.Place(District, Street) values ('CHElM', 'Damazego Tilgnera');
insert into dbo.Place(District, Street) values ('CHElM', 'Topazowa');
insert into dbo.Place(District, Street) values ('CHElM', 'Uranowa');
insert into dbo.Place(District, Street) values ('CHElM', 'Wawelska');
insert into dbo.Place(District, Street) values ('CHElM', 'Jozefa Wąsika');
insert into dbo.Place(District, Street) values ('CHElM', 'Kazimierza Wielkiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Wielkopolska 48 do konca');
insert into dbo.Place(District, Street) values ('CHElM', 'prof. Jozefa Wieckowskiego');
insert into dbo.Place(District, Street) values ('CHElM', 'Wigierska');
insert into dbo.Place(District, Street) values ('CHElM', 'Wilanowska');
insert into dbo.Place(District, Street) values ('CHElM', 'Wincentego Witosa');
insert into dbo.Place(District, Street) values ('CHElM', 'Stanislawa Worcella');
insert into dbo.Place(District, Street) values ('CHElM', 'bpa Andrzeja Wronki');
insert into dbo.Place(District, Street) values ('CHElM', 'Zamiejska');
insert into dbo.Place(District, Street) values ('CHElM', 'gen. Elzbiety Zawackiej');
insert into dbo.Place(District, Street) values ('CHElM', 'Zielonogorska');
insert into dbo.Place(District, Street) values ('CHElM', 'Zlota');
insert into dbo.Place(District, Street) values ('CHElM', 'Jerzego Zwierkowskiego');
insert into dbo.Place(District, Street) values ('OSOWA', 'kpt. Konstantego Maciejewicza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Marsa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Merkurego');
insert into dbo.Place(District, Street) values ('OSOWA', 'Meteorytowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Miedzygwiezdna');
insert into dbo.Place(District, Street) values ('OSOWA', 'Minerwy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Mirandy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Mysliborska');
insert into dbo.Place(District, Street) values ('OSOWA', 'Nawigatorow');
insert into dbo.Place(District, Street) values ('OSOWA', 'Neptuna');
insert into dbo.Place(District, Street) values ('OSOWA', 'Mieczyslawa Niedzialkowskiego');
insert into dbo.Place(District, Street) values ('OSOWA', 'Nike');
insert into dbo.Place(District, Street) values ('OSOWA', 'Nowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Nowy swiat');
insert into dbo.Place(District, Street) values ('OSOWA', 'Odyseusza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Okretowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Orfeusza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Oriona');
insert into dbo.Place(District, Street) values ('OSOWA', 'Osowski Zakątek');
insert into dbo.Place(District, Street) values ('OSOWA', 'Otago');
insert into dbo.Place(District, Street) values ('OSOWA', 'Owczarnia');
insert into dbo.Place(District, Street) values ('OSOWA', 'Ozyrysa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Parkingowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Parkowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Parterowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Parysa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Pegaza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Penelopy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Perseusza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Plac sw. Jana Apostola');
insert into dbo.Place(District, Street) values ('OSOWA', 'Planetarna');
insert into dbo.Place(District, Street) values ('OSOWA', 'Plejady');
insert into dbo.Place(District, Street) values ('OSOWA', 'Plutona');
insert into dbo.Place(District, Street) values ('OSOWA', 'Posejdona');
insert into dbo.Place(District, Street) values ('OSOWA', 'Prometeusza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Rabatki');
insert into dbo.Place(District, Street) values ('OSOWA', 'Regatowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Relaksowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Saturna');
insert into dbo.Place(District, Street) values ('OSOWA', 'Seleny');
insert into dbo.Place(District, Street) values ('OSOWA', 'prof. Michala Siedleckiego');
insert into dbo.Place(District, Street) values ('OSOWA', 'Smugowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Stanislawa Soldka');
insert into dbo.Place(District, Street) values ('OSOWA', 'Sopocka');
insert into dbo.Place(District, Street) values ('OSOWA', 'Spacerowa 46 do konca');
insert into dbo.Place(District, Street) values ('OSOWA', 'Sportowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Strzelca');
insert into dbo.Place(District, Street) values ('OSOWA', 'Syriusza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Wladyslawa Szafera');
insert into dbo.Place(District, Street) values ('OSOWA', 'Szalupowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Leonida Teligi');
insert into dbo.Place(District, Street) values ('OSOWA', 'Temidy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Tezeusza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Trapowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Urana');
insert into dbo.Place(District, Street) values ('OSOWA', 'Victorii');
insert into dbo.Place(District, Street) values ('OSOWA', 'Wegi');
insert into dbo.Place(District, Street) values ('OSOWA', 'Tadeusza Wendy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Wenus');
insert into dbo.Place(District, Street) values ('OSOWA', 'Westy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Willowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Wodnika');
insert into dbo.Place(District, Street) values ('OSOWA', 'Wolarza');
insert into dbo.Place(District, Street) values ('OSOWA', 'Woźnicy');
insert into dbo.Place(District, Street) values ('OSOWA', 'Mariusza Zaruskiego');
insert into dbo.Place(District, Street) values ('OSOWA', 'Zatokowa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Zeusa');
insert into dbo.Place(District, Street) values ('OSOWA', 'Zlotowska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Maciejkowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Macierzankowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Malinowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Franciszka Mamuszki');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Marcowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Maszynowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Metalowcow');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Mezowska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Miechucinska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Mirachowska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Montazystow');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Nagietkowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Niegocinska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Nowatorow');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Okolna');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Osiedlowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Otominska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Porzeczkowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Poziomkowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Przyrodnikow');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Rakietowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Rokitnikowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Rozwojowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Stok Rozany Stok');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Rumiankowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Sianowska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Sierakowicka');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Sierpniowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Smegorzynska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Snycerzy');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Sominska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Stoklosy');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Storczykowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Sudomska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Sulminska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Swarzewska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Szafranowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Brata Alberta sw. Brata Alberta');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Transportowcow');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Tuchomska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Tymiankowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Wdzydzka');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Wesierska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Widlinska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Wiecka');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Wielewska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Wiosenna');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Wrzesniowa');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Zbąszynska');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'Zbiezna');
insert into dbo.Place(District, Street) values ('KOKOSZKI', 'zukowska');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Macierzy Szkolnej w Gdansku');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Jozefa Mehoffera');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Piotra Michalowskiego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Piotra Norblina');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Romana i Apolonii Ogryczakow');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Aleksandra Orlowskiego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'dr. Wladyslawa Paneckiego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Polanki 59-118');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Aleksandra Potyraly');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Henryka Rodakowskiego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Aleksandra Rylkego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Henryka Siemiradzkiego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Kazimierza Sosnickiego');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'VII Dwor');
insert into dbo.Place(District, Street) values ('NOWY DWoR', 'Wita Stwosza 96-104');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Antoniego Madalinskiego 1, 1A');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Malomiejska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Mostowa');
insert into dbo.Place(District, Street) values ('WOJCIECH-LIPCE', 'Nad Starą Radunią');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Nakielska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Niegowo');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Niegowska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Nowiny');
insert into dbo.Place(District, Street) values ('WOJCIECH-LIPCE', 'Park Orunski');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Perlowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Piaskowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Plac Orunski');
insert into dbo.Place(District, Street) values ('WOJCIECH-LIPCE', 'Po Schodkach');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Podmiejska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Starą Radunią Nad Starą Radunią');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Schodkach Po Schodkach');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Poleska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Torze Przy Torze');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Przybrzezna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Przyjemna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Ptasia 1-29; 2-22A');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Radunicka');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Radunska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Stefana Ramulta');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Tadeusza Rejtana');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Rowna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Rubinowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Rzeczna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Sandomierska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Serbska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Smetna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Smolenska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Smolna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Starogardzka 1-20');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Stroma');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Szafirowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Szkocka');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Ryszarda Tomczaka');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Trakt sw. Wojciecha');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Turkusowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Ubocze');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Ukosna');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Urocza');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Wąwoz');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Wolynska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Wschodnia');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Zamiejska 1-28');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Zawiejska');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Zawilcowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'Związkowa');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'zabia');
insert into dbo.Place(District, Street) values ('PIECKI-MIGOWO', 'zulawska');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Magellana');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Heleny Marusarzowny');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Morenowa');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Morenowe Wzgorze');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'prof. Stefana Myczkowskiego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Mysliwska 20 do konca');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Mysliwskie Wzgorze');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Zofii Nalkowskiej');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Alfreda Nobla');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Oranska');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Blaise’a Pascala');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Ludwika Pasteura');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Piecewska');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Piekarnicza');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Powstania Kosciuszkowskiego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Listopadowego Powstania Listopadowego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Styczniowego Powstania Styczniowego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'prof. Mariana Raciborskiego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Franciszka Rakoczego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Wyrobka Romana Wyrobka');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Szczodra');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Lipy Trzy Lipy');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Aleksandra Volty');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Warnenska');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Widok');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Wilenska 37-63');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Wolkowyska');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Franciszka Zablockiego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Zacna');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Związku Jaszczurczego');
insert into dbo.Place(District, Street) values ('UJEsCISKO-lOSTOWICE', 'Jozefa zylewicza');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'ksiedza Jana Majdera');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Malborska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Morawska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'II Msciwoja II');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Obotrycka');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Piastowska 19-107; 20-88');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Plac Najswietszej Maryi Panny');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Poznanska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Pucka');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Aleja Rzeczypospolitej strona niezamieszkala');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Rzepichy');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Sambora');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Slowianska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Slupska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Jana Solikowskiego');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Subislawa 1-18');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Szczecinska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'sląska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'swietopelka');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Tolkmicka');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Wladyslawowska');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'I Zgody I');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'II Zgody II');
insert into dbo.Place(District, Street) values ('PRZYMORZE MAlE', 'Ziemowita');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Majewskich');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Janusza Meissnera');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Augustyna Necla');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Park im. Jana Pawla II');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Millenium Gdanska Park Millenium Gdanska Inne');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Plac Trzeciego Tysiąclecia');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Gdanskiej Polonii Gdanskiej');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Powstancow Wielkopolskich');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'Henryka Wieczorkiewicza');
insert into dbo.Place(District, Street) values ('ZASPA-ROZSTAJE', 'zwirki i Wigury');
insert into dbo.Place(District, Street) values ('OLIWA', 'Aleksandra Majkowskiego');
insert into dbo.Place(District, Street) values ('OLIWA', 'Bernarda Milewskiego');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stefana Miraua');
insert into dbo.Place(District, Street) values ('OLIWA', 'Nadwodna');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stanislawa Noakowskiego');
insert into dbo.Place(District, Street) values ('OLIWA', 'bpa. Edmunda Nowickiego');
insert into dbo.Place(District, Street) values ('OLIWA', 'Obroncow Westerplatte');
insert into dbo.Place(District, Street) values ('OLIWA', 'Opacka');
insert into dbo.Place(District, Street) values ('OLIWA', 'Wladyslawa Orkana');
insert into dbo.Place(District, Street) values ('OLIWA', 'Park Oliwski im. Adama Mickiewicza');
insert into dbo.Place(District, Street) values ('OLIWA', 'Piastowska');
insert into dbo.Place(District, Street) values ('OLIWA', 'Dworcowy Plac Dworcowy');
insert into dbo.Place(District, Street) values ('OLIWA', 'Plac Inwalidow Wojennych');
insert into dbo.Place(District, Street) values ('OLIWA', 'Poczty Gdanskiej');
insert into dbo.Place(District, Street) values ('OLIWA', 'Podhalanska');
insert into dbo.Place(District, Street) values ('OLIWA', 'Polanki 1-58');
insert into dbo.Place(District, Street) values ('OLIWA', 'Pomorska');
insert into dbo.Place(District, Street) values ('OLIWA', 'Opata Jacka Rybinskiego');
insert into dbo.Place(District, Street) values ('OLIWA', 'Sarnia');
insert into dbo.Place(District, Street) values ('OLIWA', 'Artura Schopenhauera');
insert into dbo.Place(District, Street) values ('OLIWA', 'Sloneczna');
insert into dbo.Place(District, Street) values ('OLIWA', 'Sobolowa');
insert into dbo.Place(District, Street) values ('OLIWA', 'Spacerowa');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stary Rynek Oliwski');
insert into dbo.Place(District, Street) values ('OLIWA', 'swierkowa');
insert into dbo.Place(District, Street) values ('OLIWA', 'Tatrzanska');
insert into dbo.Place(District, Street) values ('OLIWA', 'Kazimierza Tetmajera');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stanislawa Wąsowicza');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stwosza Wita Stwosza 1-62A');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stanislawa Witkiewicza');
insert into dbo.Place(District, Street) values ('OLIWA', 'Zacisze');
insert into dbo.Place(District, Street) values ('OLIWA', 'Zajecza');
insert into dbo.Place(District, Street) values ('OLIWA', 'Stefana zeromskiego');
insert into dbo.Place(District, Street) values ('OLIWA', 'zubrowa');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Majowa');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Maki');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Miedza');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Miodowa');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Modra');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Na Szancach');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Niezapominajek');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Niwki');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Olszynska');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Osiedle');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Ostrozek');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Pasieczna');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Piwonii');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Pusta');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Sierpowa');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Slonecznikowa');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Stokrotki');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Szarotki');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'sciezki');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Tulipanow');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Wąskotorowa');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Wilgi');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Wspolna');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Zagony');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Zawodzie');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Zielna');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'Zuchow');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'zarnowiecka');
insert into dbo.Place(District, Street) values ('OLSZYNKA', 'zurawia');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Kornela Makuszynskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Stanislawa Malachowskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Jana Matejki');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Matki Polki');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Miedziana');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Migowska');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'ks. Leona Miszewskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Na Wzgorzu');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Gabriela Narutowicza');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Cypriana Kamila Norwida');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Obywatelska');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Karola Olszewskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Rozy Ostrowskiej');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Akademicki Park Akademicki Inne');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Partyzantow');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Stanislawa Pawlowskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Szczepana Pileckiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Grzegorza Piramowicza');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Plac Jerzego Kolodziejskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wladyslawa Pniewskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Podlesna');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wincentego Pola');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Politechniczna');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Aleksandra Puszkina');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Renesansowa');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wladyslawa Reymonta');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Rodzinna');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Romanska');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Eugeniusza Romera');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Secesyjna');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Siedlicka');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Henryka Sienkiewicza');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Antoniego Slonimskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Juliusza Slowackiego 1-81; 2-90');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Jana Sobieskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Sobotki');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Sosnowa');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Srebrniki');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Stanislawa Staszica');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Suwalska');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wladyslawa Syrokomli');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Topolowa');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Romualda Traugutta 16-102; 31-121');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Trawki');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Jana Uphagena');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Ludwika Warynskiego 1-8; 40 do konca');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Jozefa Wassowskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wilenska 1-35; 2-42');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wlasna Strzecha');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Zygmunta Wroblewskiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Wspolczesna');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Zabytkowa');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'ks. Jozefa Zator Przytockiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Franciszka Zubrzyckiego');
insert into dbo.Place(District, Street) values ('SIEDLCE', 'Aleja Zwyciestwa 16/17 do 32');
